### ISSUE TITLE
TypeError: instance.get is not a function (when using "raw: true" with findAll)

### ISSUE THREAD

**Issue by saiban-ali** [DanielHreben/sequelize-transparent-cache#80]
query:
`const result = Model1.cache('key').findAll({ raw: true })`

Stacktrace:

> middleware TypeError: instance.get is not a function
>   middleware     at instanceToData (/home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/cache/util.js:2:19)
>   middleware     at Array.map (<anonymous>)
>   middleware     at Object.saveAll (/home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/cache/index.js:35:36)
>   middleware     at /home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/methods/class.js:53:38
>   middleware     at processImmediate (internal/timers.js:456:21)
>   middleware From previous event:
>   middleware     at /home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/methods/class.js:53:14
>   middleware     at runMicrotasks (<anonymous>)
>   middleware     at processTicksAndRejections (internal/process/task_queues.js:97:5) +0ms
>   middleware Error Caught in Async Middleware TypeError: instance.get is not a function
>   middleware     at instanceToData (/home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/cache/util.js:2:19)
>   middleware     at Array.map (<anonymous>)
>   middleware     at Object.saveAll (/home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/cache/index.js:35:36)
>   middleware     at /home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/methods/class.js:53:38
>   middleware     at processImmediate (internal/timers.js:456:21)
>   middleware From previous event:
>   middleware     at /home/saiban/techclan/admin-portal/node_modules/sequelize-transparent-cache/src/methods/class.js:53:14
>   middleware     at runMicrotasks (<anonymous>)
>   middleware     at processTicksAndRejections (internal/process/task_queues.js:97:5) +7ms

**Comment by usb248** [comment]
Same error

**Comment by DanielHreben** [comment]
Ugh oh. I think it should be a way to work around this. I do not have too much time to fix this straightway, so PRs are welcome.
